### ISSUE TITLE
How severalwordshashtaglist.txt does work ?

### ISSUE THREAD

**Issue by iGormilhit** [chaica/feed2tweet#31]
Hi,

First, thanks for this `feed2tweet`, it's very handy.

I'm trying to use `feed2tweet` to send my last post on my [shaarli](https://id-libre.org/shaarli) to my [twitter account](https://twitter.com/igor_milhit), and it does work.

But I don't understand what the `several_words_hashtags_list` parameter does. I thought I could had in the `severalwordshashtaglist.txt` file some words to use as hashtags. So I wrote into that file two words : veille shaarli, and thought that they would be rended as hashtags: `#veille` and `#shaarli`. But it doesn't. Instead, the only hashtag that `feed2tweet` is using, is the first tag of my shaarli posts tags.

What I'm doing and understanding wrong ?

The setting in my `feed2tweet.ini`:

```
[hashtaglist]
several_words_hashtags_list: severalwordshashtagslist.txt
```
The name of the file, which is in the same directory as `feed2tweet.ini`: `severalwordshashtagslist.txt`

The content of the `severalwordshashtagslist.txt` (I tried to had more entries, but the first line is what I'd like to have):

```
veille shaarli
information science
open source
logiciel libre
```

**Comment by chaica** [comment]
Thanks for the feedback.

severalwordshashtagslist.txt is only used for hashtags that appear like two or more words in the RSS feed and must be joined in to be a valid Twitter hashtag, e.g. you do have a tag "open source" from the RSS feed and because it is not a valid Twitter hashtags, feed2tweet joins the two words in only one to produce "opensource" without space. Another example is "high-availability" => "highavailability".

**Comment by iGormilhit** [comment]
Ok, now I understand it right ! :smiley: Thanks.

**Comment by chaica** [comment]
Ok :) Closing.
