### ISSUE TITLE
dynamic oauth

### ISSUE THREAD

**Issue by anarcat** [chaica/feed2tweet#9]
it should be possible to automatically configure this to use oauth without having to register a new app for each install... other software (say Turpial) do this fine, although they do fire up a web browser to use your existing session...

**Comment by anarcat** [comment]
is this something that interests you? do you need help setting up default consumer keys so that there is a way to run feed2tweet without any prior configuration?

how about using libturpial?

**Comment by chaica** [comment]
We won't implement oauth support for now. closing.

**Comment by anarcat** [comment]
wow, that's too bad - i had a PR ready to go: it just needed to be updated... if i refresh #13, would you merge it?

**Comment by chaica** [comment]
Yes I would. The current **[twitter]** section of the configuration file related to the credentials are the following ones:
```
[twitter]
consumer_key=...
consumer_secret=...
access_token=...
access_token_secret=...
```
Given what options appear in the #13, the **[twitter]** section in the configuration file to manage the oauth case would be something like:
```
consumer_key=...
consumer_secret=...
request_token_url=...
access_token_url=...
authorize_token_url=...
```
Is it what you aim for and is it ok for you? because we will need managing both authentication cases.

**Comment by anarcat** [comment]
i do not think there needs to be different authentication cases - we get a token and token_secret back from twitter's API...

**Comment by anarcat** [comment]
see #48 for this now.
